### ISSUE TITLE
Gay Man flag request! 

### ISSUE THREAD

**Issue by audeity** [mrbrendanjs/fitbit-clockface-progress#2]
**What flag do you want added**
Please describe what flag you'd like to see added to the watchface, and what part of the LGBTQIA+ community it represents. If there is a specific name for this flag or if this is a specific variation of another flag please also include that in the description (ie *Progress Pride* instead of just **pride**).
I'd like to see the Gay Man Pride Flag added! 

**What does this flag look like**
Please link to a representative image of this flag, or upload an image of the flag here.
![image](https://user-images.githubusercontent.com/86068201/122429900-bffc8080-cf58-11eb-98c4-c14a3099ef0c.png)
There's also a simplified version with five stripes, but I'd really like to see this one specifically.

**Comment by bjhawk** [comment]
This has been added! This should roll out with the next update which i'll build/upload shortly.

Look for the update rolling out 18 or 19 june. No idea how long it takes the fitbit network to catch up after an update.
