### ISSUE TITLE
Gilbert Baker Diversity flag request

### ISSUE THREAD

**Issue by audeity** [mrbrendanjs/fitbit-clockface-progress#3]
**What flag do you want added**
Please describe what flag you'd like to see added to the watchface, and what part of the LGBTQIA+ community it represents. If there is a specific name for this flag or if this is a specific variation of another flag please also include that in the description (ie *Progress Pride* instead of just **pride**).

I apologize for putting in two requests--this will be the only other one I make. Before he passed, Gilbert Baker made another variant of his original pride flag with an added lavender stripe symbolizing diversity--I've seen this called the Diversity Pride flag, and I've also seen it called the Gilbert Baker Diversity Pride flag. It's meant, I believe, to be somewhat of a companion to the Philly Pride Flag.

**What does this flag look like**
Please link to a representative image of this flag, or upload an image of the flag here.
![image](https://user-images.githubusercontent.com/86068201/122430970-a60f6d80-cf59-11eb-8eaa-c903ac767f44.png)

**Comment by bjhawk** [comment]
This has been added! I will likely build/release the update after i also add the flag for #2 but that shouldn't take me long either.

Look for the update rolling out 18 or 19 june.
