### ISSUE TITLE
Puppy Pride

### ISSUE THREAD

**Issue by acuatico69** [mrbrendanjs/fitbit-clockface-progress#4]
![flat,550x550,075,f u2](https://user-images.githubusercontent.com/22513717/126877787-fe5288b8-27c8-4792-a51e-f9f49ba231a1.jpg)
![R](https://user-images.githubusercontent.com/22513717/126877789-247ee6ae-c199-48b1-937b-c3634465112b.jpeg)
![R](https://user-images.githubusercontent.com/22513717/126877790-aa84380c-722b-4e2a-bbe3-7f1baef025f0.png)
![APHC-Large-Flag-1024x683](https://user-images.githubusercontent.com/22513717/126877791-f85b5ee3-4e38-4e2c-b531-f0992cb86d70.png)
**What flag do you want added**
Please describe what flag you'd like to see added to the watchface, and what part of the LGBTQIA+ community it represents. If there is a specific name for this flag or if this is a specific variation of another flag please also include that in the description (ie *Progress Pride* instead of just **pride**).

**What does this flag look like**
Please link to a representative image of this flag, or upload an image of the flag here.

**Comment by bjhawk** [comment]
Thanks for the request! Sorry about the delay, the Pup pride flag is up, along with a Pup Bone icon.

I went for the second flag you listed as it seems the most widely used at the moment.

You can access the app here, version 1.1.4 with this flag is published (but the description update is still pending).

https://gallery.fitbit.com/details/2d371384-a08e-4181-994c-f7522f848807
